name: 'general_framework_assets_flutter'
description: 'General Framework Library for help you create project more easy with general standarization style code base'
version: '0.0.0'
homepage: 'https://github.com/azkadev/general_framework'
environment: 
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^3.0.0'
flutter: null
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://github.com/azkadev/general_framework/issues'
documentation: 'https://github.com/azkadev/general_framework/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
