include: package:general_framework/lints/lints.yaml
linter:
  rules:
    - public_member_api_docs
analyzer:
  exclude:
    - template/
    - dev/
    - test
    - dev
    - templates
    - lib/templates
formatter:
  page_width: 9999999999
