name: 'general_framework'
description: 'General Framework Library for help you create project more easy with general standarization style code base'
version: '0.0.25'
homepage: 'https://github.com/azkadev/general_framework'
repository: 'https://github.com/azkadev/general_framework'
documentation: 'https://azkadev.github.io/general_framework/'
funding:
  - 'https://github.com/sponsors/azkadev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
executables:
  general_framework: 'general_framework'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  path: '^1.9.0'
  general_lib: '^0.0.65'
  general_lib_flutter: '^0.0.41'
  packagex: '^0.0.85'
  http: '^1.2.2'
  server_universe: '^0.0.36'
  path_provider: '^2.1.5'
  io_universe: '^0.0.5'
  intl: '^0.20.1'
  markdown: '^7.2.2'
  highlight: '^0.7.0'
  flutter_highlight: '^0.7.0'
  url_launcher: '^6.3.1'
  visibility_detector: '^0.4.0+2'
  scroll_to_index: '^3.0.1'
  media_kit_video_fork: '^0.0.2'
  html: '^0.15.4'
  translate_client: '^0.0.11'
  window_manager: '^0.4.3'
  general_system_device: '^0.0.50'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
dev_dependencies:
  flutter_lints: '^5.0.0'
  msix: '^3.16.7'
flutter:
  assets:
    - 'README.md'
packagex:
  name: 'general_framework'
  dart_target: 'general_framework'
  flutter_target: 'main'
  dart_name: 'general_framework'
  flutter_name: 'general_framework'
  is_without_platform_name: true
  flutter_commands:
    obfuscate: true
    split-debug-info: '0.0.0'
    build-name: '0.0.0'
    build-number: 1
    split-per-abi: true
    no-tree-shake-icons: true
  project_id: 'azkadev.packagex'
  github_username: 'azkadev'
  github_is_org: false
  is_app_auto_clean_up_folder: true
  flutter_build_arguments: []
  dart_compile_exe_arguments: []
  uploads:
    - platform_type: 'github'
      github_username: 'archivon-apps-stores'
      github_tag: 'release'
      github_is_org: false
      github_repository_name: 'general_framework'
    - platform_type: 'supabase'
      supabase_folder_name: 'release'
    - platform_type: 'telegram'
      telegram_chats:
        - chat_id: '@slebew'
          message_thread_id: ''
  packages:
    - dart_target: 'general_framework'
      flutter_target: 'main'
      dart_name: 'general_framework'
      flutter_name: 'general_framework'
      output_name: 'general-framework'
msix_config:
  display_name: 'general_framework'
  install_certificate: false
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
project:
  type: ''
