name: 'general_framework'
description: 'General Framework Library for help you create project more easy with general standarization style code base'
version: '0.0.0'
homepage: 'https://github.com/azkadev/general_framework'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://github.com/azkadev/general_framework/issues'
documentation: 'https://github.com/azkadev/general_framework/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
executables: 
  general_framework: 'general_framework'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  meta: '^1.11.0'
  path: '^1.9.0'
  mason_logger: '^0.2.15'
  general_lib: '^0.0.44'
  general_lib_flutter: '^0.0.25'
  packagex: '^0.0.59'
  http: '^1.1.0'
  server_universe: '^0.0.19'
  general: '^0.0.29'
  qr_lib: 
    path: '/home/galaxeus/.pub-cache/hosted/pub.dev/qr_lib-0.0.0'
dependency_overrides: 
  meta: '^1.12.0'
  pointycastle: '3.8.0'
dev_dependencies: 
  flutter_lints: '^4.0.0'
flutter: 
  assets: 
    - 'README.md'
publish_to: 'none'
