name: 'general_framework'
description: 'General Framework Library for help you create project more easy with general standarization style code base'
version: '0.0.31'
homepage: 'https://github.com/azkadev/general_framework'
repository: 'https://github.com/azkadev/general_framework'
documentation: 'https://azkadev.github.io/general_framework/'
funding:
  - 'https://github.com/sponsors/azkadev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
executables:
  general_framework: 'general_framework'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  path: '^1.9.0'
  general_lib: '^0.0.71'
  general_lib_flutter: '^0.0.42'
  http: '^1.3.0'
  server_universe: '^0.0.38'
  path_provider: '^2.1.5'
  io_universe: '^0.0.8'
  intl: '^0.20.1'
  markdown: '^7.3.0'
  highlight: '^0.7.0'
  flutter_highlight: '^0.7.0'
  url_launcher: '^6.3.1'
  visibility_detector: '^0.4.0+2'
  scroll_to_index: '^3.0.1'
  html: '^0.15.5'
  translate_client: '^0.0.11'
  window_manager: '^0.4.3'
  general_system_device: '^0.0.56'
  general_schema: '^0.0.2'
  flutter_svg: '^2.0.10+1'
  file_picker: '^9.0.2'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
dev_dependencies:
  flutter_lints: '^5.0.0'
  msix: '^3.16.7'
flutter:
  assets: 
    - packages/general_framework/assets/images/characters/abc-warriors-characters/
    - packages/general_framework/assets/images/characters/adventure-time-cartoon/
    - packages/general_framework/assets/images/characters/animation-characters/
    - packages/general_framework/assets/images/characters/bt21/
    - packages/general_framework/assets/images/characters/cinema-symbols/
    - packages/general_framework/assets/images/characters/dc-characters/
    - packages/general_framework/assets/images/characters/futurama/
    - packages/general_framework/assets/images/characters/gaming/
    - packages/general_framework/assets/images/characters/houses-of-game-of-thrones/
    - packages/general_framework/assets/images/characters/marvel-characters/
    - packages/general_framework/assets/images/characters/movie-characters/
    - packages/general_framework/assets/images/characters/naruto/
    - packages/general_framework/assets/images/characters/other/
    - packages/general_framework/assets/images/characters/star-trek-movie/
    - packages/general_framework/assets/images/characters/star-wars-movie/
    - packages/general_framework/assets/images/characters/steven-universe/
    - packages/general_framework/assets/images/characters/the-matrix/
    - packages/general_framework/assets/images/characters/the-simpsons-movie/
    # Flags SVG images
    - packages/general_framework/assets/images/logos/flags/
    # Logos SVG images
    - packages/general_framework/assets/images/logos/adobe/
    - packages/general_framework/assets/images/logos/apple/
    - packages/general_framework/assets/images/logos/browsers/
    - packages/general_framework/assets/images/logos/cinema/
    - packages/general_framework/assets/images/logos/clothing-brands/
    - packages/general_framework/assets/images/logos/cloud-storage/
    - packages/general_framework/assets/images/logos/creative-software/
    - packages/general_framework/assets/images/logos/crypto-currency/
    - packages/general_framework/assets/images/logos/eating-places/
    - packages/general_framework/assets/images/logos/ecommerce/
    - packages/general_framework/assets/images/logos/education/
    - packages/general_framework/assets/images/logos/enterprise/
    - packages/general_framework/assets/images/logos/google-services/
    - packages/general_framework/assets/images/logos/hardware/
    - packages/general_framework/assets/images/logos/hosting/
    - packages/general_framework/assets/images/logos/icons8/
    - packages/general_framework/assets/images/logos/marketing/
    - packages/general_framework/assets/images/logos/messengers/
    - packages/general_framework/assets/images/logos/microsoft/
    - packages/general_framework/assets/images/logos/military-symbols/
    - packages/general_framework/assets/images/logos/music/
    - packages/general_framework/assets/images/logos/networks/
    - packages/general_framework/assets/images/logos/other/
    - packages/general_framework/assets/images/logos/photo-and-video/
    - packages/general_framework/assets/images/logos/publishing/
    - packages/general_framework/assets/images/logos/search-engines/
    - packages/general_framework/assets/images/logos/social-bookmarking/
    - packages/general_framework/assets/images/logos/social-media/
    - packages/general_framework/assets/images/logos/software-development/
    - packages/general_framework/assets/images/logos/sports/
    - packages/general_framework/assets/images/logos/streaming/
    - packages/general_framework/assets/images/logos/transport/
    - packages/general_framework/assets/images/logos/travel/
    - packages/general_framework/assets/images/logos/utilities/
    - packages/general_framework/assets/images/logos/video-games/
    # Popular SVG images
    - packages/general_framework/assets/images/popular/common-actions/
    - packages/general_framework/assets/images/popular/documents-and-folders/
    - packages/general_framework/assets/images/popular/other/
    - packages/general_framework/assets/images/popular/settings/
    - packages/general_framework/assets/images/popular/social-media/
    - packages/general_framework/assets/images/popular/status/
    - packages/general_framework/assets/images/popular/website-sections/
  fonts:
    - family: 'AntDesign'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/AntDesign.ttf'
    - family: 'Bootstrap'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/Bootstrap.ttf'
    - family: 'BoxIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/BoxIcons.ttf'
    - family: 'Clarity'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/Clarity.ttf'
    - family: 'EvaIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/EvaIcons.ttf'
    - family: 'FontAwesome'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/FontAwesome.ttf'
    - family: 'HeroIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/HeroIcons.ttf'
    - family: 'Iconsax'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/Iconsax.ttf'
    - family: 'IonIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/IonIcons.ttf'
    - family: 'LineAwesome'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/LineAwesome.ttf'
    - family: 'MingCute'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/MingCute.ttf'
    - family: 'OctIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/OctIcons.ttf'
    - family: 'PixelartIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/PixelArtIcons.ttf'
    - family: 'TeenyIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/TeenyIcons.ttf'
    - family: 'ZondIcons'
      fonts:
        - asset: 'packages/general_framework/assets/fonts/ZondIcons.ttf' 
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC' 