name: general_framework
description: "General Framework Library for help you create project more easy with general standarization style code base"
version: 0.0.2
homepage: 'https://github.com/azkadev/general_framework'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://github.com/azkadev/general_framework/issues'
documentation: 'https://github.com/azkadev/general_framework/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null

executables:
  general_framework: general_framework

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  path: ^1.9.0
  mason_logger: ^0.2.15
  general_lib: ^0.0.41
dependency_overrides: 
  meta: ^1.12.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 