name: 'general_framework_project'
description: 'General Framework Library for help you create project more easy with general standarization style code base'
version: '0.0.4'
repository: 'https://github.com/azkadev/general_framework'
homepage: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://github.com/azkadev/general_framework/issues'
documentation: 'https://azkadev.github.io/general_framework/'
funding:
  - 'https://github.com/sponsors/azkadev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.66'
  mason_logger: '^0.3.1'
  packagex: '^0.0.85'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.3'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.1'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: ''
