name: 'general_framework_flutter'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/general_framework'
repository: 'https://github.com/{main_username_owner}/general_framework'
issue_tracker: 'https://github.com/{main_username_owner}/general_framework/issues'
documentation: 'https://github.com/{main_username_owner}/general_framework/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  general_lib: '^0.0.36'
  general_lib_flutter: '^0.0.19'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  general_framework: '^0.0.0'
  general_framework_dart: '^0.0.0'
  general_framework_scheme: '^0.0.0'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: null
