name: base_template_general_framework_project_client_isar_scheme
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  base_template_general_framework_project_scheme:
    path: ../base_template_general_framework_project_scheme  
  isar: '^4.0.0-dev.14'
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: 'any'