name: 'general_framework_server'
description: 'General Framework Library for help you create project more easy with general standarization style code base'
version: '0.0.0'
homepage: 'https://github.com/azkadev/general_framework'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://github.com/azkadev/general_framework/issues'
documentation: 'https://github.com/azkadev/general_framework/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
