name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.6'
  path: '^1.9.1'
  general_lib: '^0.0.65'
  base_web_template_general_framework_project_flutter:
    path: '../'
  base_web_template_general_framework_project_client:
    path: '../../base_web_template_general_framework_project_client'
  base_web_template_general_framework_project_secret:
    path: '../../base_web_template_general_framework_project_secret'
  general_framework: '^0.0.24'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  uses-material-design: true
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
documentation: 'https://youtube.com/@azkadev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
project:
  type: ''
