name: 'base_template_general_framework_project_api_server'
description: 'A sample command-line application.'
version: '1.0.0'
publish_to: 'none'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  server_universe: '^0.0.19'
  general_lib: '^0.0.44'
  path: '^1.9.0'
  http: '^1.2.2'
  base_template_general_framework_project_secret: 
    path: '../base_template_general_framework_project_secret'
  base_template_general_framework_project_scheme: 
    path: '../base_template_general_framework_project_scheme'
  base_template_general_framework_project_api: 
    path: '../base_template_general_framework_project_api'
  base_template_general_framework_project_api_database: 
    path: '../base_template_general_framework_project_api_database'
  general_framework: 
    path: '../../../../'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://t.me'
documentation: 'https://youtube.com/@azkadev'
