name: 'app_template_general_framework_project_flutter'
description: 'A new Flutter package project.'
version: '0.0.1'
homepage: null
environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^4.0.0'
flutter: null
dependency_overrides:
  pointycastle: '3.8.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
repository: 'https://github.com/azkadev/general_framework'
documentation: 'https://youtube.com/@azkadev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
