name: 'base_web_template_general_framework_project_flutter'
description: 'A new Flutter package project.'
version: '0.0.1'
homepage: 'https://youtube.com/@azkadev'
publish_to: 'none'
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  path: '^1.9.0'
  general_lib: '^0.0.46'
  general_lib_flutter: '^0.0.27'
  general: '^0.0.30'
  base_web_template_general_framework_project_scheme: 
    path: '../base_web_template_general_framework_project_scheme'
  base_web_template_general_framework_project_client_database: 
    path: '../base_web_template_general_framework_project_client_database'
  base_web_template_general_framework_project_client: 
    path: '../base_web_template_general_framework_project_client'
  base_web_template_general_framework_project_secret: 
    path: '../base_web_template_general_framework_project_secret'
  general_framework: '^0.0.4'
  media_kit_libs_video: '^1.0.5'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^4.0.0'
flutter: null
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
repository: 'https://github.com/azkadev/general_framework'
documentation: 'https://youtube.com/@azkadev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
