name: 'general_framework_isar_scheme'
description: 'A sample command-line application.'
version: '0.0.0'
environment: 
  sdk: '^3.3.0'
dependencies: null
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
repository: 'https://github.com/{main_username_owner}/general_framework'
homepage: 'https://github.com/{main_username_owner}/general_framework'
issue_tracker: 'https://github.com/{main_username_owner}/general_framework/issues'
documentation: 'https://github.com/{main_username_owner}/general_framework/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
