name: 'base_template_general_framework_project_api'
description: 'A sample command-line application.'
version: '1.0.0'
publish_to: none
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  base_template_general_framework_project_scheme:
    path: ../base_template_general_framework_project_scheme
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
